[package]
name = "butil"
version = "0.0.0"
edition = "2024"

[lib]
name = "butil"
path = "src/lib.rs"

[dependencies]
serde = { version = "1.0.229", features = ["derive"] }
async-trait = { version = "0.1.91" }
tokio-util = { version = "0.7.19" }
tokio = { version = "1.53.1", features = ["sync", "rt", "macros", "time"] }
tokio-stream = { version = "0.1" }
futures = "0.3"
atomic_enum = "0.3.0"
prost = "0.14"
uuid = { version = "1.24.0", features = ["v4", "serde"], optional = true }
chrono = { version = "0.4", optional = true }
serde_json = { version = "1.0.151", optional = true }
js-sys = { version = "0.3", optional = true }
minijinja = { version = "2" }
toml = { version = "1.1.4", optional = true }
sea-orm = { version = "2.0.1", features = ["sqlx-postgres", "sqlx-sqlite", "runtime-tokio-rustls"], optional = true }
lettre = { version = "0.11.23", default-features = false, features = ["tokio1-rustls", "builder", "smtp-transport", "rustls-native-certs", "aws-lc-rs", "file-transport"], optional = true }
redis = { version = "1", features = ["tokio-rustls-comp", "aio"], optional = true }

[features]
default = []

db = ["db-pg", "db-sqlite"]
db-pg = [
  "sea-orm/sqlx-postgres",
  "db-base"
]
db-sqlite = [
  "sea-orm/sqlx-sqlite",
  "db-base"
]
db-base = [
  "sea-orm/runtime-tokio-rustls"
]

mail = [
  "mail-smtp",
  "mail-file"
]
mail-file = [
  "lettre/file-transport",
  "mail-base"
]
mail-smtp = [
  "lettre/smtp-transport",
  "lettre/rustls-native-certs",
  "lettre/aws-lc-rs",
  "mail-base"
]
mail-base = [
  "lettre/tokio1-rustls",
  "tokio",
  "tokio/fs"
]

storage = [
  "storage-local"
]
storage-local = ["storage-base"]
storage-base = ["tokio/fs"]

cache-redis = ["tokio", "dep:redis", "dep:serde_json"]

fixture-loader = ["db-base", "dep:toml"]

tokio = ["dep:uuid", "dep:chrono"]
actor-redis = ["tokio", "dep:redis", "dep:serde_json"]
js = ["dep:js-sys"]
